"""adicionar campos completos no Bank

Revision ID: 3f8a53afd978
Revises: ce3d5282f0b3
Create Date: 2025-10-16 18:31:46.577279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3f8a53afd978'
down_revision: Union[str, Sequence[str], None] = 'ce3d5282f0b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banks', sa.Column('external_id', sa.String(length=36), nullable=False, comment='Identificador externo único (UUID gerado automaticamente)'))
    op.add_column('banks', sa.Column('full_name', sa.String(length=255), nullable=False, comment='Nome completo do banco'))
    op.add_column('banks', sa.Column('ispb', sa.String(length=20), nullable=True, comment='Código ISPB do banco (Identificador de Sistema de Pagamentos Brasileiro)'))
    op.add_column('banks', sa.Column('country', sa.String(length=2), nullable=False, comment='País do banco (padrão BR)'))
    op.alter_column('banks', 'id',
               existing_type=mysql.INTEGER(),
               comment='Identificador único do banco',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('banks', 'name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               comment='Nome curto ou sigla do banco',
               existing_nullable=False)
    op.alter_column('banks', 'code',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               comment='Código do banco utilizado em sistemas nacionais',
               existing_nullable=False)
    op.drop_index(op.f('code'), table_name='banks')
    op.create_unique_constraint(None, 'banks', ['external_id'])
    op.drop_column('banks', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banks', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'banks', type_='unique')
    op.create_index(op.f('code'), 'banks', ['code'], unique=True)
    op.alter_column('banks', 'code',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='Código do banco utilizado em sistemas nacionais',
               existing_nullable=False)
    op.alter_column('banks', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='Nome curto ou sigla do banco',
               existing_nullable=False)
    op.alter_column('banks', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Identificador único do banco',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('banks', 'country')
    op.drop_column('banks', 'ispb')
    op.drop_column('banks', 'full_name')
    op.drop_column('banks', 'external_id')
    # ### end Alembic commands ###
