"""migration inicial

Revision ID: 1bd5e4e489d7
Revises: 
Create Date: 2025-10-16 19:37:05.699500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1bd5e4e489d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('extra_data', sa.JSON(), nullable=True, comment='Metadados adicionais da conta'))
    op.drop_column('bank_accounts', 'json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('json', mysql.JSON(), nullable=True, comment='Metadados adicionais da conta'))
    op.drop_column('bank_accounts', 'extra_data')
    # ### end Alembic commands ###
