"""...

Revision ID: 50cc5a62f516
Revises: 1bd5e4e489d7
Create Date: 2025-10-16 19:50:15.382855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '50cc5a62f516'
down_revision: Union[str, Sequence[str], None] = '1bd5e4e489d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('cost_boleto', sa.Float(), nullable=True, comment='Custo por emissão de boleto simples'))
    op.add_column('bank_accounts', sa.Column('cost_boleto_hybrid', sa.Float(), nullable=True, comment='Custo por emissão de boleto híbrido'))
    op.add_column('bank_accounts', sa.Column('cost_pix_in', sa.Float(), nullable=True, comment='Custo para recebimento via Pix'))
    op.add_column('bank_accounts', sa.Column('cost_pix_out', sa.Float(), nullable=True, comment='Custo para envio via Pix'))
    op.alter_column('bank_accounts', 'external_id',
               existing_type=mysql.VARCHAR(length=36),
               comment='Identificador externo único (UUID)',
               existing_comment='Identificador externo único da conta (UUID)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_accounts', 'external_id',
               existing_type=mysql.VARCHAR(length=36),
               comment='Identificador externo único da conta (UUID)',
               existing_comment='Identificador externo único (UUID)',
               existing_nullable=True)
    op.drop_column('bank_accounts', 'cost_pix_out')
    op.drop_column('bank_accounts', 'cost_pix_in')
    op.drop_column('bank_accounts', 'cost_boleto_hybrid')
    op.drop_column('bank_accounts', 'cost_boleto')
    # ### end Alembic commands ###
