"""migration inicial

Revision ID: 6bd15f58d2b7
Revises: 47aa88fd74a7
Create Date: 2025-10-18 14:57:05.087300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd15f58d2b7'
down_revision: Union[str, Sequence[str], None] = '47aa88fd74a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_types',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID interno do tipo de transação'),
    sa.Column('external_id', sa.String(length=36), nullable=True, comment='Identificador externo único (UUID)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nome do tipo de transação (ex: PIX_IN)'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Descrição do tipo de transação'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Status do tipo de transação (ativo/inativo)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_transaction_types_external_id'), 'transaction_types', ['external_id'], unique=True)
    op.create_index(op.f('ix_transaction_types_id'), 'transaction_types', ['id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID interno da carteira'),
    sa.Column('external_id', sa.String(length=36), nullable=True, comment='Identificador externo único (UUID)'),
    sa.Column('name', sa.String(length=120), nullable=False, comment='Nome da carteira (ex: Carteira Principal)'),
    sa.Column('holder_name', sa.String(length=255), nullable=False, comment='Nome do titular da conta'),
    sa.Column('document', sa.String(length=20), nullable=False, comment='Documento do titular (CPF, CNPJ ou passaporte)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status da conta (ativo/inativo)'),
    sa.Column('fee_pix_in', sa.Float(), nullable=True, comment='Taxa cobrada por transação Pix de entrada'),
    sa.Column('fee_pix_out', sa.Float(), nullable=True, comment='Taxa cobrada por transação Pix de saída'),
    sa.Column('fee_boleto', sa.Float(), nullable=True, comment='Taxa cobrada por emissão de boleto'),
    sa.Column('fee_bolepix', sa.Float(), nullable=True, comment='Taxa cobrada por transação BolePix'),
    sa.Column('fee_credit_card', sa.Float(), nullable=True, comment='Taxa cobrada por transação via cartão de crédito'),
    sa.Column('fee_debit_card', sa.Float(), nullable=True, comment='Taxa cobrada por transação via cartão de débito'),
    sa.Column('balance', sa.Float(), nullable=True, comment='Saldo atual da carteira'),
    sa.Column('currency', sa.String(length=10), nullable=True, comment='Moeda associada à carteira'),
    sa.Column('bank_account_id', sa.Integer(), nullable=True, comment='ID da conta bancária associada'),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_external_id'), 'wallets', ['external_id'], unique=True)
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID único da transação'),
    sa.Column('wallet_id', sa.Integer(), nullable=False, comment='ID da carteira relacionada'),
    sa.Column('type_id', sa.Integer(), nullable=False, comment='ID do tipo de transação'),
    sa.Column('account_id', sa.Integer(), nullable=False, comment='ID da conta bancária associada'),
    sa.Column('payment_method', sa.Enum('pix', 'boleto', 'bolepix', 'card', name='paymentmethod'), nullable=False, comment='Método de pagamento: pix, boleto, bolepix, card'),
    sa.Column('txid', sa.String(length=128), nullable=True, comment='Identificador único da transação (TxID)'),
    sa.Column('end_to_end_id', sa.String(length=128), nullable=True, comment='End-to-End ID para rastreamento do pagamento'),
    sa.Column('amount', sa.Float(), nullable=False, comment='Valor da transação'),
    sa.Column('balance', sa.Float(), nullable=True, comment='Saldo após a transação (impacto na carteira/conta)'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Descrição da transação'),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='transactionstatus'), nullable=True, comment='Status da transação: pending, completed, failed'),
    sa.Column('payer', sa.JSON(), nullable=True, comment='Dados do pagador (nome, documento, banco, agência, conta, tipo de conta, ISPB)'),
    sa.Column('receiver', sa.JSON(), nullable=True, comment='Dados do recebedor (nome, documento, banco, agência, conta, tipo de conta, ISPB)'),
    sa.Column('payment_date', sa.DateTime(), nullable=True, comment='Data de pagamento efetiva da transação'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Data de criação do registro'),
    sa.Column('event_date', sa.DateTime(), nullable=True, comment='Data do evento associado à transação'),
    sa.Column('details', sa.JSON(), nullable=True, comment='Dados adicionais específicos do método de pagamento (ex: QR code Pix, linha digitável Boleto, parcelas Cartão)'),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['transaction_types.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('end_to_end_id'),
    sa.UniqueConstraint('txid')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_external_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_transaction_types_id'), table_name='transaction_types')
    op.drop_index(op.f('ix_transaction_types_external_id'), table_name='transaction_types')
    op.drop_table('transaction_types')
    # ### end Alembic commands ###
