"""create wallets table

Revision ID: b44607be809b
Revises: 50cc5a62f516
Create Date: 2025-10-17 16:40:41.446005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b44607be809b'
down_revision: Union[str, Sequence[str], None] = '50cc5a62f516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_external_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='ID interno da carteira'),
    sa.Column('external_id', mysql.VARCHAR(length=36), nullable=True, comment='Identificador externo único (UUID)'),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False, comment='Nome da carteira (ex: Carteira Principal)'),
    sa.Column('holder_name', mysql.VARCHAR(length=255), nullable=False, comment='Nome do titular da conta'),
    sa.Column('document', mysql.VARCHAR(length=20), nullable=False, comment='Documento do titular (CPF, CNPJ ou passaporte)'),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False, comment='Status da conta (ativo/inativo)'),
    sa.Column('fee_pix_in', mysql.FLOAT(), nullable=True, comment='Taxa cobrada por transação Pix de entrada'),
    sa.Column('fee_pix_out', mysql.FLOAT(), nullable=True, comment='Taxa cobrada por transação Pix de saída'),
    sa.Column('fee_boleto', mysql.FLOAT(), nullable=True, comment='Taxa cobrada por emissão de boleto'),
    sa.Column('fee_bolepix', mysql.FLOAT(), nullable=True, comment='Taxa cobrada por transação BolePix'),
    sa.Column('fee_credit_card', mysql.FLOAT(), nullable=True, comment='Taxa cobrada por transação via cartão de crédito'),
    sa.Column('fee_debit_card', mysql.FLOAT(), nullable=True, comment='Taxa cobrada por transação via cartão de débito'),
    sa.Column('balance', mysql.FLOAT(), nullable=True, comment='Saldo atual da carteira'),
    sa.Column('currency', mysql.VARCHAR(length=10), nullable=True, comment='Moeda associada à carteira'),
    sa.Column('bank_account_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='ID da conta bancária associada'),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], name=op.f('wallets_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_index(op.f('ix_wallets_external_id'), 'wallets', ['external_id'], unique=True)
    # ### end Alembic commands ###
